version: '3'

services:
  
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    ports: 
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app

    