"""test

Revision ID: 12e3d2d8a783
Revises: 68de0c02fc84
Create Date: 2021-12-09 12:31:42.310839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e3d2d8a783'
down_revision = '68de0c02fc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
